Simple effect
disparter/combat-sheet pull request #10
Opened 2022-08-13 17:45 UTC by disparter

Created Simple Effect Concept for the Bot
Now every time a round is forward it will check to ending the effects on the battle characters
Age Initiative Table is showing the effects applied on each character
Created command to apply an effect on a target character
Created command to remove and effect on a target character

2022-08-13 18:00 UTC, micaelcosmo approved these changes
News are reviewed and approved.

2022-08-14 13:41 UTC, BlueMage-Code requested changes

2022-08-14 13:41 UTC, BlueMage-Code commented on src/main/java/com/dis/bot/exception/EffectNotFoundException.java
> +public class EffectNotFoundException extends CharacterException {
"extends EffectException"

2022-08-14 13:45 UTC, BlueMage-Code approved these changes

2022-08-14 13:45 UTC, merged